### ISSUE TITLE
有点疑问想请教一下

### ISSUE THREAD

**Issue by lwq1365102044** [miniLV/MVC-Demo#1]
我看了一下代码，发现你在model之外，又用到了一个Demo1Datas类，这还是mvc架构吗？

**Comment by miniLV** [comment]
这个其实不太算MVC的架构，因为网络数据请求层是剥离的，这个Demo1Datas 可以看成是 Service 层，专门处理网络请求服务的~，而Model层就存放普通的 Json 模型就行了
